sampling_rate: 22050
model_name: LSTM_net
hyperparameters:
  epochs: 1000
  batch_size: 128
  learning_rate: 2e-4
  frame_length: 88
  input_type: ["msp"]
  output_type: ["ppgmat"]
  seed: 1234
  jvs: true
  pseudo: true
  whisper: true

model_params:
  n_inputs: 80
  n_outputs: 80
  n_layers: 2
  hidden_size: 128
  fc_size: 4096
  dropout: 0.2
  bidirectional: true
  continuous: false
  l2softmax: false
