sampling_rate: 22050
model_name: LSTM_net
hyperparameters:
  epochs: 3000
  batch_size: 128
  learning_rate: 2e-4
  frame_length: 88
  input_type: ['msp']
  output_type: ['ppgmat'] # Phoneme Posterior Gram
  seed: 1234
  jvs: true
  pseudo: true
  whisper: true
  special: false

model_params:
  in_channels: 80
  hidden_channels: 256
  out_channels: 36  # 音素数
  kernel_size: 3
  dilation_rate: 2
  n_layers: 4
  p_dropout: 0.1
  layernorm: true
  activation: "gate"
  bidirectional: true
  l2softmax: false
  continuous: false
  fc_size: 128
