hyperparameters:
  batch_size: 128
  epochs: 3000
  frame_length: 88
  input_type:
  - msp
  jvs: true
  learning_rate: 2e-4
  output_type:
  - ppgmat
  pseudo: true
  seed: 1234
  special: false
  whisper: true
model_name: LSTM_net
model_params:
  activation: gate
  bidirectional: true
  continuous: false
  dilation_rate: 2
  fc_size: 128
  hidden_channels: 256
  in_channels: 80
  kernel_size: 3
  l2softmax: false
  layernorm: true
  n_layers: 4
  out_channels: 36
  p_dropout: 0.1
sampling_rate: 22050
